#Pipeline1
name: Auto Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "bathiniarunkumar147@gmail.com"
          git config --global user.name "bathiniarun"

      - name: Merge pull request
        id: merge
        run: |
          git fetch origin
          git checkout -b Feature1 origin/Feature1
          git checkout main
          git merge --no-ff --no-commit Feature1
          if git ls-files -u | grep -q "^[12]" ; then
            echo "Merge conflict detected"
            git merge --abort
            exit 1
          else
            git commit -m "Merge pull request #${{ github.event.pull_request.number }} from Feature1"
            git push origin main
            exit 0
          fi