#Pipeline1
name: Auto Merge Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "bathiniarunkumar147@gmail.com"
          git config --global user.name "bathiniarun"

      - name: Merge pull request
        id: merge
        run: |
          git fetch origin
          git checkout -b Feature1 origin/Feature1
          git checkout main
          git merge --no-ff --no-commit Feature1
          if git ls-files -u | grep -q "^[12]" ; then
            echo "Merge conflict detected"
            git merge --abort
            exit 1
          else
            git commit -m "Merge pull request #${{ github.event.pull_request.number }} from Feature1"
            git push origin main
            exit 0
          fi

      - name: Send email on merge conflict
        if: failure()
        uses: bathiniarun/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Merge conflict detected in pull request #${{ github.event.pull_request.number }}"
          body: "Merge conflict detected in pull request #${{ github.event.pull_request.number }}. Please resolve the conflicts and merge manually."
          to: "bathiniarunkumar525@gmail.com"
          tls: true

      - name: Set pull request status
        if: success()
        uses: arun/create-pull-request-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Pull request auto-merged successfully!"
